/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.13
 * Generated at: 2022-03-18 23:27:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"IMG/jamia.ico\" type=\"image/ico\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/practice.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-3.3.6-dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-3.3.6-dist\\font-awesome-4.7.0\\css\\font-awesome.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-3.3.6-dist\\font-awesome-4.7.0\\css\\font-awesome-min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"bootstrap-3.3.6-dist/js/jquery-2.2.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"bootstrap-3.3.6-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>REGISTER</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("li a:hover, .dropdown:hover .dropbtn {\r\n");
      out.write("    background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li.dropdown {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("    min-width: 160px;\r\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("    color: black;\r\n");
      out.write("    padding: 12px 16px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a:hover {background-color: #f1f1f1}\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover .dropdown-content {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #eaeaea;\">\r\n");

if((session.getAttribute("user_id"))!=null&&(session.getAttribute("pass_word")!=null))
{

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    }
    else
    {
    
      out.write("\r\n");
      out.write("    ");
      if (true) {
        _jspx_page_context.forward("index.jsp");
        return;
      }
      out.write("\r\n");
      out.write("    ");

     }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-2\">\r\n");
      out.write("                <a href=\"\"><center><img src=\"IMG/150px-Jamia_Millia_Islamia_Logo.svg.png\" style=\"height: 100px; width: 100px; margin-top: 20px;\"></center></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-8\">\r\n");
      out.write("                <center>\r\n");
      out.write("                <h1>JAMIA MILLIA ISLAMIA<br>\r\n");
      out.write("                <span style=\"font-size: 30px;\">(A Central University)</span><br>\r\n");
      out.write("                <span style=\"font-size: 20px;\">NAAC Accredited 'A' Grade</span></h1>\r\n");
      out.write("                </center>\r\n");
      out.write("            </div >\r\n");
      out.write("            <div class=\"col-sm-2\">\r\n");
      out.write("            </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\" list nav navbar\">\r\n");
      out.write("    <ul class=\" nav navbar-nav \">\r\n");
      out.write("            <li class=\"dropdown\"><a href=\"javascript:void(0)\" class=\"dropbtn\"><span class=\"glyphicon glyphicon-log-in\"></span>&nbsp;&nbsp;VIEW</a>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("      			<a href=\"View_stu.jsp\">View Student</a>\r\n");
      out.write("      			<a href=\"View_fclty.jsp\">View Faculty</a>\r\n");
      out.write("      		</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"dropdown\"><a href=\"javascript:void(0)\" class=\"dropbtn\"><span class=\"glyphicon glyphicon-time\"></span>&nbsp;&nbsp;UPDATE</a>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("      			<a href=\"update.jsp\">Update Student</a>\r\n");
      out.write("      			<a href=\"update_fclty.jsp\">Update Faculty</a>\r\n");
      out.write("      		</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"dropdown\"><a href=\"javascript:void(0)\" class=\"dropbtn\"><span class=\"glyphicon glyphicon-trash\"></span>&nbsp;&nbsp;DELETE</a>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("      			<a href=\"delete.jsp\">Delete Student</a>\r\n");
      out.write("      			<a href=\"delete_fclty.jsp\">Delete Faculty</a>\r\n");
      out.write("      		</div>\r\n");
      out.write("      		</li>\r\n");
      out.write("            <li class=\"dropdown\"><a href=\"javascript:void(0)\" class=\"dropbtn\"><span class=\"glyphicon glyphicon-edit\"></span>&nbsp;&nbsp;REGISTER</a>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("      			<a href=\"register.jsp\">Register Student</a>\r\n");
      out.write("      			<a href=\"register_fclty.jsp\">Register Faculty</a>\r\n");
      out.write("      		</div>\r\n");
      out.write("            </li>\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        <li ><a href=\"profile.jsp\"  style=\"background-color: #eaeaea ; border-radius: 20px;\" id=\"qwe\"><span class=\"glyphicon glyphicon-user\" style=\"font-size: 18px;\"></span>&nbsp;&nbsp;");
      out.print(session.getAttribute("user_name"));
      out.write("<br></a></li>&nbsp; \r\n");
      out.write("        <a href=\"index.jsp\" style=\"padding: 10px; text-decoration: none; color: #ffffff;\" id=\"off\"><button class=\"btn btn-danger\" style=\"padding: 13px; border-radius: 20px;\"><span class=\"glyphicon glyphicon-off\" style=\"font-size: 18px; color: white;\"></span><span style=\"color: white; font-size:20px; padding: 5px;\">&nbsp;&nbsp;Sign Out</span></button></a>&nbsp; &nbsp;\r\n");
      out.write("    </ul>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"container-fluid\" id=\"listdown\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-2\" style=\"height: 100px;\">\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-8\"  style=\"height: 100px;\">\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-2\"  style=\"height: 100px;\">\r\n");
      out.write("              \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div style=\";\">\r\n");

String res=(String)request.getAttribute("reg");
		if(res!=null)
		{
		
      out.write("\r\n");
      out.write("		<label style=\"font-weight: bold;\">");
      out.print(res);
      out.write("</label>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("     <form action=\"StudentServ\" method=\"post\"> \r\n");
      out.write("        <div class=\"form-group container\" style=\" font-weight: bold; border: dotted 3px green ; padding: 20px;\">    \r\n");
      out.write("            <div class=\"input-group\">\r\n");
      out.write("                <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\r\n");
      out.write("                <input type=\"text\" placeholder=\"First Name\" name=\"first_name\" class=\"form-control\" style=\"width: 50%;\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"Last Name\" name=\"last_name\" class=\"form-control\" style=\"width: 50%;\">\r\n");
      out.write("                <label class=\"input-group-addon\"><span style=\"font-weight: bolder;\">DATE OF BIRTH</span></label>\r\n");
      out.write("                <input type=\"text\" name=\"stu_DOB\" class=\"form-control\">\r\n");
      out.write("            </div>\r\n");
      out.write("<div >\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <label class=\"input-group-addon\" ><span style=\"font-weight: bolder;\">Father-Name &nbsp;</span></label>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Name\" name=\"father_name\"class=\"form-control\">\r\n");
      out.write("                    <label class=\"input-group-addon\" ><span style=\"font-weight: bolder;\">Mother-Name</span></label>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Name\" name=\"mother_name\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div style=\"border-top: dotted 3px grey; padding-top: 10px;\">\r\n");
      out.write("                <div class=\"input-group\" >\r\n");
      out.write("                    <label class=\"input-group-addon\"><span style=\"font-weight: bolder;\">ADDRESS</span></label>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Line 1 (BUILDING NO, STREET ,LOCALITY)\" class=\"form-control\" name=\"addr1\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"Line 2 (DISTRICT , LANDMARK)\" name =\"addr2\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\" style=\"width: 80%\">\r\n");
      out.write("                    <label class=\"input-group-addon\"><span style=\"font-weight: bolder;\">STATE</span></label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"State-Name\" name=\"S_state\">\r\n");
      out.write("\r\n");
      out.write("                    <label class=\"input-group-addon\"><span style=\"font-weight: bolder;\">COUNTRY</span></label>\r\n");
      out.write("                    <select  class=\"form-control\" name=\"S_country\">\r\n");
      out.write("                        <option value=\"AF\">Afghanistan</option>\r\n");
      out.write("                        <option value=\"AL\">Albania</option>\r\n");
      out.write("                        <option value=\"DZ\">Algeria</option>\r\n");
      out.write("                        <option value=\"AS\">American Samoa</option>\r\n");
      out.write("                        <option value=\"AD\">Andorra</option>\r\n");
      out.write("                        <option value=\"AO\">Angola</option>\r\n");
      out.write("                        <option value=\"AU\">Australia</option>\r\n");
      out.write("                        <option value=\"AT\">Austria</option>\r\n");
      out.write("                        <option value=\"AZ\">Azerbaijan</option>\r\n");
      out.write("                        <option value=\"BS\">Bahamas</option>\r\n");
      out.write("                        <option value=\"BH\">Bahrain</option>\r\n");
      out.write("                        <option value=\"BD\">Bangladesh</option>\r\n");
      out.write("                        <option value=\"BB\">Barbados</option>\r\n");
      out.write("                        <option value=\"BY\">Belarus</option>\r\n");
      out.write("                        <option value=\"BE\">Belgium</option>\r\n");
      out.write("                        <option value=\"BZ\">Belize</option>\r\n");
      out.write("                        <option value=\"BJ\">Benin</option>\r\n");
      out.write("                        <option value=\"BM\">Bermuda</option>\r\n");
      out.write("                        <option value=\"BT\">Bhutan</option>\r\n");
      out.write("                        <option value=\"BO\">Bolivia</option>\r\n");
      out.write("                        <option value=\"BA\">Bosnia and Herzegowina</option>\r\n");
      out.write("                        <option value=\"BW\">Botswana</option>\r\n");
      out.write("                        <option value=\"BV\">Bouvet Island</option>\r\n");
      out.write("                        <option value=\"BR\">Brazil</option>\r\n");
      out.write("                        <option value=\"IO\">British Indian Ocean Territory</option>\r\n");
      out.write("                        <option value=\"BN\">Brunei Darussalam</option>\r\n");
      out.write("                        <option value=\"BG\">Bulgaria</option>\r\n");
      out.write("                        <option value=\"BF\">Burkina Faso</option>\r\n");
      out.write("                        <option value=\"BI\">Burundi</option>\r\n");
      out.write("                        <option value=\"KH\">Cambodia</option>\r\n");
      out.write("                        <option value=\"CM\">Cameroon</option>\r\n");
      out.write("                        <option value=\"CA\">Canada</option>\r\n");
      out.write("                        <option value=\"CV\">Cape Verde</option>\r\n");
      out.write("                        <option value=\"KY\">Cayman Islands</option>\r\n");
      out.write("                        <option value=\"CF\">Central African Republic</option>\r\n");
      out.write("                        <option value=\"TD\">Chad</option>\r\n");
      out.write("                        <option value=\"CL\">Chile</option>\r\n");
      out.write("                        <option value=\"CN\">China</option>\r\n");
      out.write("                        <option value=\"CX\">Christmas Island</option>\r\n");
      out.write("                        <option value=\"CC\">Cocos (Keeling) Islands</option>\r\n");
      out.write("                        <option value=\"CO\">Colombia</option>\r\n");
      out.write("                        <option value=\"KM\">Comoros</option>\r\n");
      out.write("                        <option value=\"CG\">Congo</option>\r\n");
      out.write("                        <option value=\"CD\">Congo, the Democratic Republic of the</option>\r\n");
      out.write("                        <option value=\"CK\">Cook Islands</option>\r\n");
      out.write("                        <option value=\"CR\">Costa Rica</option>\r\n");
      out.write("                        <option value=\"CI\">Cote d'Ivoire</option>\r\n");
      out.write("                        <option value=\"HR\">Croatia (Hrvatska)</option>\r\n");
      out.write("                        <option value=\"CU\">Cuba</option>\r\n");
      out.write("                        <option value=\"CY\">Cyprus</option>\r\n");
      out.write("                        <option value=\"CZ\">Czech Republic</option>\r\n");
      out.write("                        <option value=\"DK\">Denmark</option>\r\n");
      out.write("                        <option value=\"DJ\">Djibouti</option>\r\n");
      out.write("                        <option value=\"DM\">Dominica</option>\r\n");
      out.write("                        <option value=\"DO\">Dominican Republic</option>\r\n");
      out.write("                        <option value=\"TP\">East Timor</option>\r\n");
      out.write("                        <option value=\"EC\">Ecuador</option>\r\n");
      out.write("                        <option value=\"EG\">Egypt</option>\r\n");
      out.write("                        <option value=\"SV\">El Salvador</option>\r\n");
      out.write("                        <option value=\"GQ\">Equatorial Guinea</option>\r\n");
      out.write("                        <option value=\"ER\">Eritrea</option>\r\n");
      out.write("                        <option value=\"EE\">Estonia</option>\r\n");
      out.write("                        <option value=\"ET\">Ethiopia</option>\r\n");
      out.write("                        <option value=\"FK\">Falkland Islands (Malvinas)</option>\r\n");
      out.write("                        <option value=\"FO\">Faroe Islands</option>\r\n");
      out.write("                        <option value=\"FJ\">Fiji</option>\r\n");
      out.write("                        <option value=\"FI\">Finland</option>\r\n");
      out.write("                        <option value=\"FR\">France</option>\r\n");
      out.write("                        <option value=\"FX\">France, Metropolitan</option>\r\n");
      out.write("                        <option value=\"GF\">French Guiana</option>\r\n");
      out.write("                        <option value=\"PF\">French Polynesia</option>\r\n");
      out.write("                        <option value=\"TF\">French Southern Territories</option>\r\n");
      out.write("                        <option value=\"GA\">Gabon</option>\r\n");
      out.write("                        <option value=\"GM\">Gambia</option>\r\n");
      out.write("                        <option value=\"GE\">Georgia</option>\r\n");
      out.write("                        <option value=\"DE\">Germany</option>\r\n");
      out.write("                        <option value=\"GH\">Ghana</option>\r\n");
      out.write("                        <option value=\"GI\">Gibraltar</option>\r\n");
      out.write("                        <option value=\"GR\">Greece</option>\r\n");
      out.write("                        <option value=\"GL\">Greenland</option>\r\n");
      out.write("                        <option value=\"GD\">Grenada</option>\r\n");
      out.write("                        <option value=\"GP\">Guadeloupe</option>\r\n");
      out.write("                        <option value=\"GU\">Guam</option>\r\n");
      out.write("                        <option value=\"GT\">Guatemala</option>\r\n");
      out.write("                        <option value=\"GN\">Guinea</option>\r\n");
      out.write("                        <option value=\"GW\">Guinea-Bissau</option>\r\n");
      out.write("                        <option value=\"GY\">Guyana</option>\r\n");
      out.write("                        <option value=\"HT\">Haiti</option>\r\n");
      out.write("                        <option value=\"HM\">Heard and Mc Donald Islands</option>\r\n");
      out.write("                        <option value=\"VA\">Holy See (Vatican City State)</option>\r\n");
      out.write("                        <option value=\"HN\">Honduras</option>\r\n");
      out.write("                        <option value=\"HK\">Hong Kong</option>\r\n");
      out.write("                        <option value=\"HU\">Hungary</option>\r\n");
      out.write("                        <option value=\"IS\">Iceland</option>\r\n");
      out.write("                        <option value=\"IN\" selected=\"selected\">India</option>\r\n");
      out.write("                        <option value=\"ID\">Indonesia</option>\r\n");
      out.write("                        <option value=\"IR\">Iran (Islamic Republic of)</option>\r\n");
      out.write("                        <option value=\"IQ\">Iraq</option>\r\n");
      out.write("                        <option value=\"IE\">Ireland</option>\r\n");
      out.write("                        <option value=\"IL\">Israel</option>\r\n");
      out.write("                        <option value=\"IT\">Italy</option>\r\n");
      out.write("                        <option value=\"JM\">Jamaica</option>\r\n");
      out.write("                        <option value=\"JP\">Japan</option>\r\n");
      out.write("                        <option value=\"JO\">Jordan</option>\r\n");
      out.write("                        <option value=\"KZ\">Kazakhstan</option>\r\n");
      out.write("                        <option value=\"KE\">Kenya</option>\r\n");
      out.write("                        <option value=\"KI\">Kiribati</option>\r\n");
      out.write("                        <option value=\"KP\">Korea, Democratic People's Republic of</option>\r\n");
      out.write("                        <option value=\"KR\">Korea, Republic of</option>\r\n");
      out.write("                        <option value=\"KW\">Kuwait</option>\r\n");
      out.write("                        <option value=\"KG\">Kyrgyzstan</option>\r\n");
      out.write("                        <option value=\"LA\">Lao People's Democratic Republic</option>\r\n");
      out.write("                        <option value=\"LV\">Latvia</option>\r\n");
      out.write("                        <option value=\"LB\">Lebanon</option>\r\n");
      out.write("                        <option value=\"LS\">Lesotho</option>\r\n");
      out.write("                        <option value=\"LR\">Liberia</option>\r\n");
      out.write("                        <option value=\"LY\">Libyan Arab Jamahiriya</option>\r\n");
      out.write("                        <option value=\"LI\">Liechtenstein</option>\r\n");
      out.write("                        <option value=\"LT\">Lithuania</option>\r\n");
      out.write("                        <option value=\"LU\">Luxembourg</option>\r\n");
      out.write("                        <option value=\"MO\">Macau</option>\r\n");
      out.write("                        <option value=\"MK\">Macedonia, The Former Yugoslav Republic of</option>\r\n");
      out.write("                        <option value=\"MG\">Madagascar</option>\r\n");
      out.write("                        <option value=\"MW\">Malawi</option>\r\n");
      out.write("                        <option value=\"MY\">Malaysia</option>\r\n");
      out.write("                        <option value=\"MV\">Maldives</option>\r\n");
      out.write("                        <option value=\"ML\">Mali</option>\r\n");
      out.write("                        <option value=\"MT\">Malta</option>\r\n");
      out.write("                        <option value=\"MH\">Marshall Islands</option>\r\n");
      out.write("                        <option value=\"MQ\">Martinique</option>\r\n");
      out.write("                        <option value=\"MR\">Mauritania</option>\r\n");
      out.write("                        <option value=\"MU\">Mauritius</option>\r\n");
      out.write("                        <option value=\"YT\">Mayotte</option>\r\n");
      out.write("                        <option value=\"MX\">Mexico</option>\r\n");
      out.write("                        <option value=\"FM\">Micronesia, Federated States of</option>\r\n");
      out.write("                        <option value=\"MD\">Moldova, Republic of</option>\r\n");
      out.write("                        <option value=\"MC\">Monaco</option>\r\n");
      out.write("                        <option value=\"MN\">Mongolia</option>\r\n");
      out.write("                        <option value=\"MS\">Montserrat</option>\r\n");
      out.write("                        <option value=\"MA\">Morocco</option>\r\n");
      out.write("                        <option value=\"MZ\">Mozambique</option>\r\n");
      out.write("                        <option value=\"MM\">Myanmar</option>\r\n");
      out.write("                        <option value=\"NA\">Namibia</option>\r\n");
      out.write("                        <option value=\"NR\">Nauru</option>\r\n");
      out.write("                        <option value=\"NP\">Nepal</option>\r\n");
      out.write("                        <option value=\"NL\">Netherlands</option>\r\n");
      out.write("                        <option value=\"AN\">Netherlands Antilles</option>\r\n");
      out.write("                        <option value=\"NC\">New Caledonia</option>\r\n");
      out.write("                        <option value=\"NZ\">New Zealand</option>\r\n");
      out.write("                        <option value=\"NI\">Nicaragua</option>\r\n");
      out.write("                        <option value=\"NE\">Niger</option>\r\n");
      out.write("                        <option value=\"NG\">Nigeria</option>\r\n");
      out.write("                        <option value=\"NU\">Niue</option>\r\n");
      out.write("                        <option value=\"NF\">Norfolk Island</option>\r\n");
      out.write("                        <option value=\"MP\">Northern Mariana Islands</option>\r\n");
      out.write("                        <option value=\"NO\">Norway</option>\r\n");
      out.write("                        <option value=\"OM\">Oman</option>\r\n");
      out.write("                        <option value=\"PK\">Pakistan</option>\r\n");
      out.write("                        <option value=\"PW\">Palau</option>\r\n");
      out.write("                        <option value=\"PA\">Panama</option>\r\n");
      out.write("                        <option value=\"PG\">Papua New Guinea</option>\r\n");
      out.write("                        <option value=\"PY\">Paraguay</option>\r\n");
      out.write("                        <option value=\"PE\">Peru</option>\r\n");
      out.write("                        <option value=\"PH\">Philippines</option>\r\n");
      out.write("                        <option value=\"PN\">Pitcairn</option>\r\n");
      out.write("                        <option value=\"PL\">Poland</option>\r\n");
      out.write("                        <option value=\"PT\">Portugal</option>\r\n");
      out.write("                        <option value=\"PR\">Puerto Rico</option>\r\n");
      out.write("                        <option value=\"QA\">Qatar</option>\r\n");
      out.write("                        <option value=\"RE\">Reunion</option>\r\n");
      out.write("                        <option value=\"RO\">Romania</option>\r\n");
      out.write("                        <option value=\"RU\">Russian Federation</option>\r\n");
      out.write("                        <option value=\"RW\">Rwanda</option>\r\n");
      out.write("                        <option value=\"KN\">Saint Kitts and Nevis</option>\r\n");
      out.write("                        <option value=\"LC\">Saint LUCIA</option>\r\n");
      out.write("                        <option value=\"VC\">Saint Vincent and the Grenadines</option>\r\n");
      out.write("                        <option value=\"WS\">Samoa</option>\r\n");
      out.write("                        <option value=\"SM\">San Marino</option>\r\n");
      out.write("                        <option value=\"ST\">Sao Tome and Principe</option>\r\n");
      out.write("                        <option value=\"SA\">Saudi Arabia</option>\r\n");
      out.write("                        <option value=\"SN\">Senegal</option>\r\n");
      out.write("                        <option value=\"SC\">Seychelles</option>\r\n");
      out.write("                        <option value=\"SL\">Sierra Leone</option>\r\n");
      out.write("                        <option value=\"SG\">Singapore</option>\r\n");
      out.write("                        <option value=\"SK\">Slovakia (Slovak Republic)</option>\r\n");
      out.write("                        <option value=\"SI\">Slovenia</option>\r\n");
      out.write("                        <option value=\"SB\">Solomon Islands</option>\r\n");
      out.write("                        <option value=\"SO\">Somalia</option>\r\n");
      out.write("                        <option value=\"ZA\">South Africa</option>\r\n");
      out.write("                        <option value=\"GS\">South Georgia and the South Sandwich Islands</option>\r\n");
      out.write("                        <option value=\"ES\">Spain</option>\r\n");
      out.write("                        <option value=\"LK\">Sri Lanka</option>\r\n");
      out.write("                        <option value=\"SH\">St. Helena</option>\r\n");
      out.write("                        <option value=\"PM\">St. Pierre and Miquelon</option>\r\n");
      out.write("                        <option value=\"SD\">Sudan</option>\r\n");
      out.write("                        <option value=\"SR\">Suriname</option>\r\n");
      out.write("                        <option value=\"SJ\">Svalbard and Jan Mayen Islands</option>\r\n");
      out.write("                        <option value=\"SZ\">Swaziland</option>\r\n");
      out.write("                        <option value=\"SE\">Sweden</option>\r\n");
      out.write("                        <option value=\"CH\">Switzerland</option>\r\n");
      out.write("                        <option value=\"SY\">Syrian Arab Republic</option>\r\n");
      out.write("                        <option value=\"TW\">Taiwan, Province of China</option>\r\n");
      out.write("                        <option value=\"TJ\">Tajikistan</option>\r\n");
      out.write("                        <option value=\"TZ\">Tanzania, United Republic of</option>\r\n");
      out.write("                        <option value=\"TH\">Thailand</option>\r\n");
      out.write("                        <option value=\"TG\">Togo</option>\r\n");
      out.write("                        <option value=\"TK\">Tokelau</option>\r\n");
      out.write("                        <option value=\"TO\">Tonga</option>\r\n");
      out.write("                        <option value=\"TT\">Trinidad and Tobago</option>\r\n");
      out.write("                        <option value=\"TN\">Tunisia</option>\r\n");
      out.write("                        <option value=\"TR\">Turkey</option>\r\n");
      out.write("                        <option value=\"TM\">Turkmenistan</option>\r\n");
      out.write("                        <option value=\"TC\">Turks and Caicos Islands</option>\r\n");
      out.write("                        <option value=\"TV\">Tuvalu</option>\r\n");
      out.write("                        <option value=\"UG\">Uganda</option>\r\n");
      out.write("                        <option value=\"UA\">Ukraine</option>\r\n");
      out.write("                        <option value=\"AE\">United Arab Emirates</option>\r\n");
      out.write("                        <option value=\"GB\">United Kingdom</option>\r\n");
      out.write("                        <option value=\"US\">United States</option>\r\n");
      out.write("                        <option value=\"UM\">United States Minor Outlying Islands</option>\r\n");
      out.write("                        <option value=\"UY\">Uruguay</option>\r\n");
      out.write("                        <option value=\"UZ\">Uzbekistan</option>\r\n");
      out.write("                        <option value=\"VU\">Vanuatu</option>\r\n");
      out.write("                        <option value=\"VE\">Venezuela</option>\r\n");
      out.write("                        <option value=\"VN\">Viet Nam</option>\r\n");
      out.write("                        <option value=\"VG\">Virgin Islands (British)</option>\r\n");
      out.write("                        <option value=\"VI\">Virgin Islands (U.S.)</option>\r\n");
      out.write("                        <option value=\"WF\">Wallis and Futuna Islands</option>\r\n");
      out.write("                        <option value=\"EH\">Western Sahara</option>\r\n");
      out.write("                        <option value=\"YE\">Yemen</option>\r\n");
      out.write("                        <option value=\"YU\">Yugoslavia</option>\r\n");
      out.write("                        <option value=\"ZM\">Zambia</option>\r\n");
      out.write("                        <option value=\"ZW\">Zimbabwe</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                \r\n");
      out.write("                    <label class=\"input-group-addon\"><span style=\"font-weight: bolder;\">PIN</span></label>\r\n");
      out.write("                    <input type=\"number\" class=\"form-control\" placeholder=\"00000\" name=\"S_pin\">\r\n");
      out.write("\r\n");
      out.write("                    <label class=\"input-group-addon\"><span style=\"font-weight: bolder;\">MOBILE</span></label>\r\n");
      out.write("                    <input type=\"number\" class=\"form-control\" placeholder=\"00000000001\" name=\"S_mobile\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            \r\n");
      out.write("            <br>\r\n");
      out.write("            <div class=\"input-group\" style=\"border-top: dotted 3px grey; padding-top: 10px;\">\r\n");
      out.write("                <label class=\"input-group-addon\" ><span style=\"font-weight: bolder;\">GUARDIAN</span></label>\r\n");
      out.write("                <input type=\"text\" placeholder=\"Name\" class=\"form-control\" style=\"width: 50%;\" name=\"G_name\">\r\n");
      out.write("                <br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div >\r\n");
      out.write("                <div class=\"input-group\" >\r\n");
      out.write("                    <label class=\"input-group-addon\"><span style=\"font-weight: bolder;\">G.ADDRESS</span></label>\r\n");
      out.write("                    <input  name=\"G_addr1\"  type=\"text\" placeholder=\"Line 1 (BUILDING NO, STREET ,LOCALITY)\" class=\"form-control\">\r\n");
      out.write("                    <input name=\"G_addr2\" type=\"text\" class=\"form-control\" placeholder=\"Line 2 (DISTRICT , LANDMARK)\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\" style=\"width: 75%\">\r\n");
      out.write("                    <label class=\"input-group-addon\"><span style=\"font-weight: bolder;\">STATE</span></label>\r\n");
      out.write("                    <input name=\"G_state\" type=\"text\" class=\"form-control\" placeholder=\"State-Name\">\r\n");
      out.write("\r\n");
      out.write("                    <label class=\"input-group-addon\"><span style=\"font-weight: bolder;\">COUNTRY</span></label>\r\n");
      out.write("                    <select  class=\"form-control\" name=\"G_country\">\r\n");
      out.write("                        <option value=\"AF\">Afghanistan</option>\r\n");
      out.write("                        <option value=\"AL\">Albania</option>\r\n");
      out.write("                        <option value=\"DZ\">Algeria</option>\r\n");
      out.write("                        <option value=\"AS\">American Samoa</option>\r\n");
      out.write("                        <option value=\"AD\">Andorra</option>\r\n");
      out.write("                        <option value=\"AO\">Angola</option>\r\n");
      out.write("                        <option value=\"AI\">Anguilla</option>\r\n");
      out.write("                        <option value=\"AQ\">Antarctica</option>\r\n");
      out.write("                        <option value=\"AG\">Antigua and Barbuda</option>\r\n");
      out.write("                        <option value=\"AR\">Argentina</option>\r\n");
      out.write("                        <option value=\"AM\">Armenia</option>\r\n");
      out.write("                        <option value=\"AW\">Aruba</option>\r\n");
      out.write("                        <option value=\"AU\">Australia</option>\r\n");
      out.write("                        <option value=\"AT\">Austria</option>\r\n");
      out.write("                        <option value=\"AZ\">Azerbaijan</option>\r\n");
      out.write("                        <option value=\"BS\">Bahamas</option>\r\n");
      out.write("                        <option value=\"BH\">Bahrain</option>\r\n");
      out.write("                        <option value=\"BD\">Bangladesh</option>\r\n");
      out.write("                        <option value=\"BB\">Barbados</option>\r\n");
      out.write("                        <option value=\"BY\">Belarus</option>\r\n");
      out.write("                        <option value=\"BE\">Belgium</option>\r\n");
      out.write("                        <option value=\"BZ\">Belize</option>\r\n");
      out.write("                        <option value=\"BJ\">Benin</option>\r\n");
      out.write("                        <option value=\"BM\">Bermuda</option>\r\n");
      out.write("                        <option value=\"BT\">Bhutan</option>\r\n");
      out.write("                        <option value=\"BO\">Bolivia</option>\r\n");
      out.write("                        <option value=\"BA\">Bosnia and Herzegowina</option>\r\n");
      out.write("                        <option value=\"BW\">Botswana</option>\r\n");
      out.write("                        <option value=\"BV\">Bouvet Island</option>\r\n");
      out.write("                        <option value=\"BR\">Brazil</option>\r\n");
      out.write("                        <option value=\"IO\">British Indian Ocean Territory</option>\r\n");
      out.write("                        <option value=\"BN\">Brunei Darussalam</option>\r\n");
      out.write("                        <option value=\"BG\">Bulgaria</option>\r\n");
      out.write("                        <option value=\"BF\">Burkina Faso</option>\r\n");
      out.write("                        <option value=\"BI\">Burundi</option>\r\n");
      out.write("                        <option value=\"KH\">Cambodia</option>\r\n");
      out.write("                        <option value=\"CM\">Cameroon</option>\r\n");
      out.write("                        <option value=\"CA\">Canada</option>\r\n");
      out.write("                        <option value=\"CV\">Cape Verde</option>\r\n");
      out.write("                        <option value=\"KY\">Cayman Islands</option>\r\n");
      out.write("                        <option value=\"CF\">Central African Republic</option>\r\n");
      out.write("                        <option value=\"TD\">Chad</option>\r\n");
      out.write("                        <option value=\"CL\">Chile</option>\r\n");
      out.write("                        <option value=\"CN\">China</option>\r\n");
      out.write("                        <option value=\"CX\">Christmas Island</option>\r\n");
      out.write("                        <option value=\"CC\">Cocos (Keeling) Islands</option>\r\n");
      out.write("                        <option value=\"CO\">Colombia</option>\r\n");
      out.write("                        <option value=\"KM\">Comoros</option>\r\n");
      out.write("                        <option value=\"CG\">Congo</option>\r\n");
      out.write("                        <option value=\"CD\">Congo, the Democratic Republic of the</option>\r\n");
      out.write("                        <option value=\"CK\">Cook Islands</option>\r\n");
      out.write("                        <option value=\"CR\">Costa Rica</option>\r\n");
      out.write("                        <option value=\"CI\">Cote d'Ivoire</option>\r\n");
      out.write("                        <option value=\"HR\">Croatia (Hrvatska)</option>\r\n");
      out.write("                        <option value=\"CU\">Cuba</option>\r\n");
      out.write("                        <option value=\"CY\">Cyprus</option>\r\n");
      out.write("                        <option value=\"CZ\">Czech Republic</option>\r\n");
      out.write("                        <option value=\"DK\">Denmark</option>\r\n");
      out.write("                        <option value=\"DJ\">Djibouti</option>\r\n");
      out.write("                        <option value=\"DM\">Dominica</option>\r\n");
      out.write("                        <option value=\"DO\">Dominican Republic</option>\r\n");
      out.write("                        <option value=\"TP\">East Timor</option>\r\n");
      out.write("                        <option value=\"EC\">Ecuador</option>\r\n");
      out.write("                        <option value=\"EG\">Egypt</option>\r\n");
      out.write("                        <option value=\"SV\">El Salvador</option>\r\n");
      out.write("                        <option value=\"GQ\">Equatorial Guinea</option>\r\n");
      out.write("                        <option value=\"ER\">Eritrea</option>\r\n");
      out.write("                        <option value=\"EE\">Estonia</option>\r\n");
      out.write("                        <option value=\"ET\">Ethiopia</option>\r\n");
      out.write("                        <option value=\"FK\">Falkland Islands (Malvinas)</option>\r\n");
      out.write("                        <option value=\"FO\">Faroe Islands</option>\r\n");
      out.write("                        <option value=\"FJ\">Fiji</option>\r\n");
      out.write("                        <option value=\"FI\">Finland</option>\r\n");
      out.write("                        <option value=\"FR\">France</option>\r\n");
      out.write("                        <option value=\"FX\">France, Metropolitan</option>\r\n");
      out.write("                        <option value=\"GF\">French Guiana</option>\r\n");
      out.write("                        <option value=\"PF\">French Polynesia</option>\r\n");
      out.write("                        <option value=\"TF\">French Southern Territories</option>\r\n");
      out.write("                        <option value=\"GA\">Gabon</option>\r\n");
      out.write("                        <option value=\"GM\">Gambia</option>\r\n");
      out.write("                        <option value=\"GE\">Georgia</option>\r\n");
      out.write("                        <option value=\"DE\">Germany</option>\r\n");
      out.write("                        <option value=\"GH\">Ghana</option>\r\n");
      out.write("                        <option value=\"GI\">Gibraltar</option>\r\n");
      out.write("                        <option value=\"GR\">Greece</option>\r\n");
      out.write("                        <option value=\"GL\">Greenland</option>\r\n");
      out.write("                        <option value=\"GD\">Grenada</option>\r\n");
      out.write("                        <option value=\"GP\">Guadeloupe</option>\r\n");
      out.write("                        <option value=\"GU\">Guam</option>\r\n");
      out.write("                        <option value=\"GT\">Guatemala</option>\r\n");
      out.write("                        <option value=\"GN\">Guinea</option>\r\n");
      out.write("                        <option value=\"GW\">Guinea-Bissau</option>\r\n");
      out.write("                        <option value=\"GY\">Guyana</option>\r\n");
      out.write("                        <option value=\"HT\">Haiti</option>\r\n");
      out.write("                        <option value=\"HM\">Heard and Mc Donald Islands</option>\r\n");
      out.write("                        <option value=\"VA\">Holy See (Vatican City State)</option>\r\n");
      out.write("                        <option value=\"HN\">Honduras</option>\r\n");
      out.write("                        <option value=\"HK\">Hong Kong</option>\r\n");
      out.write("                        <option value=\"HU\">Hungary</option>\r\n");
      out.write("                        <option value=\"IS\">Iceland</option>\r\n");
      out.write("                        <option value=\"IN\" selected=\"selected\">India</option>\r\n");
      out.write("                        <option value=\"ID\">Indonesia</option>\r\n");
      out.write("                        <option value=\"IR\">Iran (Islamic Republic of)</option>\r\n");
      out.write("                        <option value=\"IQ\">Iraq</option>\r\n");
      out.write("                        <option value=\"IE\">Ireland</option>\r\n");
      out.write("                        <option value=\"IL\">Israel</option>\r\n");
      out.write("                        <option value=\"IT\">Italy</option>\r\n");
      out.write("                        <option value=\"JM\">Jamaica</option>\r\n");
      out.write("                        <option value=\"JP\">Japan</option>\r\n");
      out.write("                        <option value=\"JO\">Jordan</option>\r\n");
      out.write("                        <option value=\"KZ\">Kazakhstan</option>\r\n");
      out.write("                        <option value=\"KE\">Kenya</option>\r\n");
      out.write("                        <option value=\"KI\">Kiribati</option>\r\n");
      out.write("                        <option value=\"KP\">Korea, Democratic People's Republic of</option>\r\n");
      out.write("                        <option value=\"KR\">Korea, Republic of</option>\r\n");
      out.write("                        <option value=\"KW\">Kuwait</option>\r\n");
      out.write("                        <option value=\"KG\">Kyrgyzstan</option>\r\n");
      out.write("                        <option value=\"LA\">Lao People's Democratic Republic</option>\r\n");
      out.write("                        <option value=\"LV\">Latvia</option>\r\n");
      out.write("                        <option value=\"LB\">Lebanon</option>\r\n");
      out.write("                        <option value=\"LS\">Lesotho</option>\r\n");
      out.write("                        <option value=\"LR\">Liberia</option>\r\n");
      out.write("                        <option value=\"LY\">Libyan Arab Jamahiriya</option>\r\n");
      out.write("                        <option value=\"LI\">Liechtenstein</option>\r\n");
      out.write("                        <option value=\"LT\">Lithuania</option>\r\n");
      out.write("                        <option value=\"LU\">Luxembourg</option>\r\n");
      out.write("                        <option value=\"MO\">Macau</option>\r\n");
      out.write("                        <option value=\"MK\">Macedonia, The Former Yugoslav Republic of</option>\r\n");
      out.write("                        <option value=\"MG\">Madagascar</option>\r\n");
      out.write("                        <option value=\"MW\">Malawi</option>\r\n");
      out.write("                        <option value=\"MY\">Malaysia</option>\r\n");
      out.write("                        <option value=\"MV\">Maldives</option>\r\n");
      out.write("                        <option value=\"ML\">Mali</option>\r\n");
      out.write("                        <option value=\"MT\">Malta</option>\r\n");
      out.write("                        <option value=\"MH\">Marshall Islands</option>\r\n");
      out.write("                        <option value=\"MQ\">Martinique</option>\r\n");
      out.write("                        <option value=\"MR\">Mauritania</option>\r\n");
      out.write("                        <option value=\"MU\">Mauritius</option>\r\n");
      out.write("                        <option value=\"YT\">Mayotte</option>\r\n");
      out.write("                        <option value=\"MX\">Mexico</option>\r\n");
      out.write("                        <option value=\"FM\">Micronesia, Federated States of</option>\r\n");
      out.write("                        <option value=\"MD\">Moldova, Republic of</option>\r\n");
      out.write("                        <option value=\"MC\">Monaco</option>\r\n");
      out.write("                        <option value=\"MN\">Mongolia</option>\r\n");
      out.write("                        <option value=\"MS\">Montserrat</option>\r\n");
      out.write("                        <option value=\"MA\">Morocco</option>\r\n");
      out.write("                        <option value=\"MZ\">Mozambique</option>\r\n");
      out.write("                        <option value=\"MM\">Myanmar</option>\r\n");
      out.write("                        <option value=\"NA\">Namibia</option>\r\n");
      out.write("                        <option value=\"NR\">Nauru</option>\r\n");
      out.write("                        <option value=\"NP\">Nepal</option>\r\n");
      out.write("                        <option value=\"NL\">Netherlands</option>\r\n");
      out.write("                        <option value=\"AN\">Netherlands Antilles</option>\r\n");
      out.write("                        <option value=\"NC\">New Caledonia</option>\r\n");
      out.write("                        <option value=\"NZ\">New Zealand</option>\r\n");
      out.write("                        <option value=\"NI\">Nicaragua</option>\r\n");
      out.write("                        <option value=\"NE\">Niger</option>\r\n");
      out.write("                        <option value=\"NG\">Nigeria</option>\r\n");
      out.write("                        <option value=\"NU\">Niue</option>\r\n");
      out.write("                        <option value=\"NF\">Norfolk Island</option>\r\n");
      out.write("                        <option value=\"MP\">Northern Mariana Islands</option>\r\n");
      out.write("                        <option value=\"NO\">Norway</option>\r\n");
      out.write("                        <option value=\"OM\">Oman</option>\r\n");
      out.write("                        <option value=\"PK\">Pakistan</option>\r\n");
      out.write("                        <option value=\"PW\">Palau</option>\r\n");
      out.write("                        <option value=\"PA\">Panama</option>\r\n");
      out.write("                        <option value=\"PG\">Papua New Guinea</option>\r\n");
      out.write("                        <option value=\"PY\">Paraguay</option>\r\n");
      out.write("                        <option value=\"PE\">Peru</option>\r\n");
      out.write("                        <option value=\"PH\">Philippines</option>\r\n");
      out.write("                        <option value=\"PN\">Pitcairn</option>\r\n");
      out.write("                        <option value=\"PL\">Poland</option>\r\n");
      out.write("                        <option value=\"PT\">Portugal</option>\r\n");
      out.write("                        <option value=\"PR\">Puerto Rico</option>\r\n");
      out.write("                        <option value=\"QA\">Qatar</option>\r\n");
      out.write("                        <option value=\"RE\">Reunion</option>\r\n");
      out.write("                        <option value=\"RO\">Romania</option>\r\n");
      out.write("                        <option value=\"RU\">Russian Federation</option>\r\n");
      out.write("                        <option value=\"RW\">Rwanda</option>\r\n");
      out.write("                        <option value=\"KN\">Saint Kitts and Nevis</option>\r\n");
      out.write("                        <option value=\"LC\">Saint LUCIA</option>\r\n");
      out.write("                        <option value=\"VC\">Saint Vincent and the Grenadines</option>\r\n");
      out.write("                        <option value=\"WS\">Samoa</option>\r\n");
      out.write("                        <option value=\"SM\">San Marino</option>\r\n");
      out.write("                        <option value=\"ST\">Sao Tome and Principe</option>\r\n");
      out.write("                        <option value=\"SA\">Saudi Arabia</option>\r\n");
      out.write("                        <option value=\"SN\">Senegal</option>\r\n");
      out.write("                        <option value=\"SC\">Seychelles</option>\r\n");
      out.write("                        <option value=\"SL\">Sierra Leone</option>\r\n");
      out.write("                        <option value=\"SG\">Singapore</option>\r\n");
      out.write("                        <option value=\"SK\">Slovakia (Slovak Republic)</option>\r\n");
      out.write("                        <option value=\"SI\">Slovenia</option>\r\n");
      out.write("                        <option value=\"SB\">Solomon Islands</option>\r\n");
      out.write("                        <option value=\"SO\">Somalia</option>\r\n");
      out.write("                        <option value=\"ZA\">South Africa</option>\r\n");
      out.write("                        <option value=\"GS\">South Georgia and the South Sandwich Islands</option>\r\n");
      out.write("                        <option value=\"ES\">Spain</option>\r\n");
      out.write("                        <option value=\"LK\">Sri Lanka</option>\r\n");
      out.write("                        <option value=\"SH\">St. Helena</option>\r\n");
      out.write("                        <option value=\"PM\">St. Pierre and Miquelon</option>\r\n");
      out.write("                        <option value=\"SD\">Sudan</option>\r\n");
      out.write("                        <option value=\"SR\">Suriname</option>\r\n");
      out.write("                        <option value=\"SJ\">Svalbard and Jan Mayen Islands</option>\r\n");
      out.write("                        <option value=\"SZ\">Swaziland</option>\r\n");
      out.write("                        <option value=\"SE\">Sweden</option>\r\n");
      out.write("                        <option value=\"CH\">Switzerland</option>\r\n");
      out.write("                        <option value=\"SY\">Syrian Arab Republic</option>\r\n");
      out.write("                        <option value=\"TW\">Taiwan, Province of China</option>\r\n");
      out.write("                        <option value=\"TJ\">Tajikistan</option>\r\n");
      out.write("                        <option value=\"TZ\">Tanzania, United Republic of</option>\r\n");
      out.write("                        <option value=\"TH\">Thailand</option>\r\n");
      out.write("                        <option value=\"TG\">Togo</option>\r\n");
      out.write("                        <option value=\"TK\">Tokelau</option>\r\n");
      out.write("                        <option value=\"TO\">Tonga</option>\r\n");
      out.write("                        <option value=\"TT\">Trinidad and Tobago</option>\r\n");
      out.write("                        <option value=\"TN\">Tunisia</option>\r\n");
      out.write("                        <option value=\"TR\">Turkey</option>\r\n");
      out.write("                        <option value=\"TM\">Turkmenistan</option>\r\n");
      out.write("                        <option value=\"TC\">Turks and Caicos Islands</option>\r\n");
      out.write("                        <option value=\"TV\">Tuvalu</option>\r\n");
      out.write("                        <option value=\"UG\">Uganda</option>\r\n");
      out.write("                        <option value=\"UA\">Ukraine</option>\r\n");
      out.write("                        <option value=\"AE\">United Arab Emirates</option>\r\n");
      out.write("                        <option value=\"GB\">United Kingdom</option>\r\n");
      out.write("                        <option value=\"US\">United States</option>\r\n");
      out.write("                        <option value=\"UM\">United States Minor Outlying Islands</option>\r\n");
      out.write("                        <option value=\"UY\">Uruguay</option>\r\n");
      out.write("                        <option value=\"UZ\">Uzbekistan</option>\r\n");
      out.write("                        <option value=\"VU\">Vanuatu</option>\r\n");
      out.write("                        <option value=\"VE\">Venezuela</option>\r\n");
      out.write("                        <option value=\"VN\">Viet Nam</option>\r\n");
      out.write("                        <option value=\"VG\">Virgin Islands (British)</option>\r\n");
      out.write("                        <option value=\"VI\">Virgin Islands (U.S.)</option>\r\n");
      out.write("                        <option value=\"WF\">Wallis and Futuna Islands</option>\r\n");
      out.write("                        <option value=\"EH\">Western Sahara</option>\r\n");
      out.write("                        <option value=\"YE\">Yemen</option>\r\n");
      out.write("                        <option value=\"YU\">Yugoslavia</option>\r\n");
      out.write("                        <option value=\"ZM\">Zambia</option>\r\n");
      out.write("                        <option value=\"ZW\">Zimbabwe</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                \r\n");
      out.write("                    <label class=\"input-group-addon\"><span style=\"font-weight: bolder;\">PIN</span></label>\r\n");
      out.write("                    <input name=\"G_pin\" type=\"number\" class=\"form-control\" placeholder=\"00000\">\r\n");
      out.write("\r\n");
      out.write("                    <label class=\"input-group-addon\"><span style=\"font-weight: bolder;\">MOBILE</span></label>\r\n");
      out.write("                    <input name=\"G_mobile\" type=\"number\" class=\"form-control\" placeholder=\"00000000001\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br><br><br>\r\n");
      out.write("            <div class=\"input-group\" style=\"border-top: dotted 3px grey; padding-top: 10px;\">\r\n");
      out.write("                <label class=\"input-group-addon\" ><span style=\"font-weight: bolder;\">LAST SCHOOL</span></label>\r\n");
      out.write("                <input name=\"Last_school\" type=\"text\" placeholder=\"Name\" class=\"form-control\" style=\"width: 33%;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-group\">\r\n");
      out.write("                <label class=\"input-group-addon\" ><span style=\"font-weight: bolder;\">PERCENTAGE /CGPA</span></label>\r\n");
      out.write("                <input name=\"Last_percentage\" type=\"text\" placeholder=\"value\" class=\"form-control\" style=\"width: 33%;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-group\" style=\"padding-bottom: 10px;\">\r\n");
      out.write("                <label class=\"input-group-addon\" ><span style=\"font-weight: bolder;\">YEAR OF PASSING</span></label>\r\n");
      out.write("                <input name=\"Last_year_of_passing\" type=\"text\" placeholder=\"YEAR\" class=\"form-control\" style=\"width: 33%;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <div style=\"border-top: dotted 3px grey; padding: 20px;\">\r\n");
      out.write("                <center>\r\n");
      out.write("                <input type=\"submit\" class=\"btn btn-success\" value=\"Register\"/>\r\n");
      out.write("                        <button type=\"reset\" class=\"btn btn-danger\">RESET</button>\r\n");
      out.write("                        <input type=\"hidden\" name=\"student\" value=\"addstudent\"/> \r\n");
      out.write("                </center>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- \r\n");
      out.write("<div class=\"fotter\"> \r\n");
      out.write("        <p>&copy 2017&nbsp;Jamia Millia Islamia.&nbsp;All rights reserved<br>\r\n");
      out.write("        Site Designed & Developed by MNSR</p> \r\n");
      out.write("</div>\r\n");
      out.write(" -->\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
