/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.13
 * Generated at: 2022-03-18 21:54:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FACULTY;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class faculty_0020of_0020humanities_0020and_0020language_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../CSS/practice.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap-3.3.6-dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap-3.3.6-dist\\font-awesome-4.7.0\\css\\font-awesome.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap-3.3.6-dist\\font-awesome-4.7.0\\css\\font-awesome-min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../bootstrap-3.3.6-dist/js/jquery-2.2.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../bootstrap-3.3.6-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>FACULTY OF HUMANITIES AND LANGUAGE</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #f1f1f1\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("			<div class=\"col-sm-2\">\r\n");
      out.write("				<a href=\"\"><center><img src=\"../IMG/150px-Jamia_Millia_Islamia_Logo.svg.png\" style=\"height: 100px; width: 100px; margin-top: 20px;\"></center></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-sm-8\">\r\n");
      out.write("				<center>\r\n");
      out.write("				<h1>JAMIA MILLIA ISLAMIA<br>\r\n");
      out.write("				<span style=\"font-size: 30px;\">(A Central University)</span><br>\r\n");
      out.write("				<span style=\"font-size: 20px;\">NAAC Accredited 'A' Grade</span></h1>\r\n");
      out.write("				</center>\r\n");
      out.write("			</div >\r\n");
      out.write("			<div class=\"col-sm-2\">\r\n");
      out.write("			</div>\r\n");
      out.write("</div>\r\n");
      out.write("		<div class=\" list nav navbar\">\r\n");
      out.write("			<ul class=\" nav navbar-nav \">\r\n");
      out.write("				<li ><a href=\"../index.jsp\"><span class=\"glyphicon glyphicon-home\" style=\"font-style: none; font-size: 19px; color:black;\"></span>&nbsp;Home</a></li>&nbsp;  &nbsp; \r\n");
      out.write("				<li><a href=\"../aboutus.jsp\" ><span class=\"fa fa-bullhorn\" style=\"font-style: none; font-size: 19px;  color:black; color:black;\"></span>&nbsp;About us </a></li> &nbsp;  &nbsp;\r\n");
      out.write("				<li><a href=\"../faculty.jsp\"><span class=\"fa fa-building-o\" style=\"font-style: none; font-size: 19px;  color:black;\"></span> &nbsp;Faculty</a></li>&nbsp; &nbsp;\r\n");
      out.write("				<li><a href=\"../contact.jsp\" ><span class=\"glyphicon glyphicon-phone-alt\" style=\"font-style: none; font-size: 19px;  color:black;\"></span> &nbsp;Contact us </a></li> &nbsp; &nbsp;\r\n");
      out.write("			</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<nav class=\"breadcrumb\">\r\n");
      out.write("	<span style=\"font-weight: bolder;\">PaTh:</span>&nbsp;&nbsp;\r\n");
      out.write("  <a class=\"breadcrumb-item\" href=\"../index.jsp\">Home /</a>\r\n");
      out.write("  <a class=\"breadcrumb-item\" href=\"../faculty.jsp\">Faculty/</a>\r\n");
      out.write("  <span class=\"breadcrumb-item active\">Faculty of Humanities and Languages</span>\r\n");
      out.write("</nav>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("		<h2><span style=\"font-weight: bolder;\" id=\"hty\"><u>Faculty of Humanities and Languages</u>--</span></h2></br>\r\n");
      out.write("		<h2 style=\"font-weight: bolder;\"><u>Introduction:-</u></h2>\r\n");
      out.write("		<div style=\"font-size:17px;\">\r\n");
      out.write("			The Faculty of Humanities and Languages encompasses a whole universe of liberal education and intellectual domains that are at the centre of the growth, nurturing and development of a civilized human being. The Faculty has been established with an aim to empower the learners to systematically understand languages, literatures, histories and cultures of the world and appreciate them as humanityâs common heritage.<br> Awareness of this heritage will broaden the vision of students and help them reflect on social, political, cultural and economic structures and processes that are dynamic in nature and will play a crucial role in the nurturing of their talents .<br> The faculty is committed to provide an interdisciplinary and integrative pedagogical approach to learners and provide them a broad spectrum of subjects and courses to choose from that will suit their interests, leanings and future career profiles. Delivering a transformative education is the core mission of the Faculty\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<h3 style=\"font-weight: bolder;\"><u>Departments</u></h3>\r\n");
      out.write("		<div style=\"font-size:17px;\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>Department of Arabic</li>\r\n");
      out.write("				<li>Department of English</li>\r\n");
      out.write("				<li>Department of Hindi</li>\r\n");
      out.write("				<li>Department of Urdu</li>\r\n");
      out.write("				<li>Department of History and Culture</li>\r\n");
      out.write("				<li>Department of Islamic Studies</li>\r\n");
      out.write("				<li>Department of Persian</li>\r\n");
      out.write("				<li>Department of Tourism, Hotel, Hospitality and Heritage Studies</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"fotter\"> \r\n");
      out.write("		<p>&copy 2017&nbsp;Jamia Millia Islamia.&nbsp;All rights reserved<br>\r\n");
      out.write("		Site Designed & Developed by MNSR</p> \r\n");
      out.write("</div>>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
