/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.13
 * Generated at: 2022-03-18 21:54:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FACULTY;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class fet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../CSS/practice.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap-3.3.6-dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap-3.3.6-dist\\font-awesome-4.7.0\\css\\font-awesome.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap-3.3.6-dist\\font-awesome-4.7.0\\css\\font-awesome-min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../bootstrap-3.3.6-dist/js/jquery-2.2.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../bootstrap-3.3.6-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>FET</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #f1f1f1\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("			<div class=\"col-sm-2\">\r\n");
      out.write("				<a href=\"\"><center><img src=\"../IMG/150px-Jamia_Millia_Islamia_Logo.svg.png\" style=\"height: 100px; width: 100px; margin-top: 20px;\"></center></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-sm-8\">\r\n");
      out.write("				<center>\r\n");
      out.write("				<h1>JAMIA MILLIA ISLAMIA<br>\r\n");
      out.write("				<span style=\"font-size: 30px;\">(A Central University)</span><br>\r\n");
      out.write("				<span style=\"font-size: 20px;\">NAAC Accredited 'A' Grade</span></h1>\r\n");
      out.write("				</center>\r\n");
      out.write("			</div >\r\n");
      out.write("			<div class=\"col-sm-2\">\r\n");
      out.write("			</div>\r\n");
      out.write("</div>\r\n");
      out.write("		<div class=\" list nav navbar\">\r\n");
      out.write("			<ul class=\" nav navbar-nav \">\r\n");
      out.write("				<li ><a href=\"../index.jsp\"><span class=\"glyphicon glyphicon-home\" style=\"font-style: none; font-size: 19px; color:black;\"></span>&nbsp;Home</a></li>&nbsp;  &nbsp; \r\n");
      out.write("				<li><a href=\"../aboutus.jsp\" ><span class=\"fa fa-bullhorn\" style=\"font-style: none; font-size: 19px;  color:black; color:black;\"></span>&nbsp;About us </a></li> &nbsp;  &nbsp;\r\n");
      out.write("				<li><a href=\"../faculty.jsp\"><span class=\"fa fa-building-o\" style=\"font-style: none; font-size: 19px;  color:black;\"></span> &nbsp;Faculty</a></li>&nbsp; &nbsp;\r\n");
      out.write("				<li><a href=\"../contact.jsp\" ><span class=\"glyphicon glyphicon-phone-alt\" style=\"font-style: none; font-size: 19px;  color:black;\"></span> &nbsp;Contact us </a></li> &nbsp; &nbsp;\r\n");
      out.write("			</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<nav class=\"breadcrumb\">\r\n");
      out.write("	<span style=\"font-weight: bolder;\">PaTh:</span>&nbsp;&nbsp;\r\n");
      out.write("  <a class=\"breadcrumb-item\" href=\"../index.jsp\">Home /</a>\r\n");
      out.write("  <a class=\"breadcrumb-item\" href=\"../faculty.jsp\">Faculty/</a>\r\n");
      out.write("  <span class=\"breadcrumb-item active\">Faculty of Engineering and Technology</span>\r\n");
      out.write("</nav>\r\n");
      out.write("<div class=\"container\" id=\"listdown\">            \r\n");
      out.write("		<h2><span style=\"font-weight: bolder;\" id=\"hty\"><u>Faculty of Engineering and Technology--</u></span></h2></br>\r\n");
      out.write("\r\n");
      out.write("		<h3><span style=\"font-weight: bolder;\" id=\"hty\">Introduction:-</span></h3>\r\n");
      out.write("		<div style=\"font-size:18px;\">\r\n");
      out.write("			The Faculty of Engineering and Technology was established in 1985 with the objective to provide outstanding engineering education directed at enriching the quality of life in an emerging knowledge-based society. The mission of the Faculty is to graduate morally conscious and highly competent engineers, conduct internationally recognized research, and provide quality professional and community services. The Faculty operates as an administrative unit within the University and thus is home to over 3000 students and over 200 academic, administrative and technical staff. At present, there are six departments in the Faculty âcivil, mechanical, electrical, electronics and communication, and computer engineering, and applied sciences and humanities. Undergraduate program leading to B. Tech. are offered in civil, mechanical, electrical, electronics and communications, and computer engineering.</br></br> The Faculty has a continuing education programs for in-service engineers leading to B. E. degree in civil, electrical, mechanical, electronics and communications, and computer engineering. The faculty also offers postgraduate programs â M. Tech. (Environmental Sciences and Engineering), M. Tech. (Earthquake Engineering), M. Tech. (Electrical Power Systems Management), M. Tech. (Control and Instrumentation System), M. Tech. (Mechanical Engineering â with specialization in Thermal Engineering, Production and Industrial Engineering, and Machine Design) and M.Sc. (Electronics). The University Polytechnic offers regular and part-time (evening) courses leading to diploma in civil, electrical, mechanical, electronics and communications, and computer engineering. Research programs leading to PhD are also offered by all the departments. All courses of the Faculty are duly approved by the All India Council for Technical Education, and the medium of instruction is English for all the courses.<br><br>\r\n");
      out.write("\r\n");
      out.write("			The Faculty of Engineering and Technology is proud to have a regular faculty of more than 125 that cares about the students and their success. More than 90% of the faculty hold PhD degree from reputed institutes in India and abroad. Faculty members are actively involved in research and consultancy projects of national importance. The faculty has a deep sense of belonging to the institution and is devoted to maximizing the opportunities available to students across the campus and beyond. The Faculty of Engineering and Technology has a full-fledged training and placement office that is responsible for training and placement of students. Reputed multinational companies have consistently recruited our students through campus placements and each year a large number of its students are placed in public and private sector companies. A significant number of alumni of the Faculty are serving in the IAS, IPS and other allied services. A large number of alumni have proven their entrepreneurship skills in setting up successful enterprises. Many alumni are working as faculty and consultants in reputed institutes and organizations in India and abroad. The students of the Faculty have access to a Faculty library that is equipped with modern e-learning tools apart from consortium of INDEST and INFLIBNET, and a large collection of text and reference books. A centralized computer laboratory with more than 100 terminals is available to students in addition to similar laboratories available in each department. Centralized University facilities available to our students include free access to Ansari health centre, sports complex, dental services, and University library.</br></br>\r\n");
      out.write("\r\n");
      out.write("			The Faculty is currently executing several infrastructure development projects to cater to its future needs. The future developmental plans of the Faculty include introduction of new undergraduate and postgraduate programs in emerging areas, complete automation of examination system, modernization and automation of Faculty library, creation of a Wi-fi campus, development of smart classrooms, and introduction of course credit-transfer arrangements with institutions in India and abroad.\r\n");
      out.write("		</div>\r\n");
      out.write("		<div style=\"font-size:18px;\">\r\n");
      out.write("			<h3 id=\"hty\"><u><b>Departments</b></u></h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>University Polytechnic</li>\r\n");
      out.write("				<li>Department of Computer Engineering</li>\r\n");
      out.write("				<li>Department of Civil Engineering</li>\r\n");
      out.write("				<li>Department of Applied Sciences & Humanities</li>\r\n");
      out.write("				<li>Department of Electrical Engineering </li>\r\n");
      out.write("				<li>Department of Mechenical Engineering</li>\r\n");
      out.write("				<li>Department of Electronics & Communication Engineering</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"fotter\"> \r\n");
      out.write("		<p>&copy 2017&nbsp;Jamia Millia Islamia.&nbsp;All rights reserved<br>\r\n");
      out.write("		Site Designed & Developed by MNSR</p> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
